# Copyright © Stéphane Raimbault <stephane.raimbault@gmail.com> and/or contibutors.
# Copyright © End 2 End Technologies, LLC., 2025.

site_name: libmodbus_e2e

theme:
    name: material
    font: false

markdown_extensions:
    - md_in_html
    - attr_list
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
